#!/usr/bin/env python3

import os
import sys
import argparse
import importlib


VENDOR_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "vendor")


def main():
    sys.path.append(VENDOR_PATH)
    margo = importlib.import_module("margo")

    parser = argparse.ArgumentParser()
    parser.add_argument("in_file")  # TODO: use argparse.FileType
    parser.add_argument(
        "-o", "--out", default="-",
        type=argparse.FileType("w", encoding="utf-8"))
    args = parser.parse_args()

    print(
        margo.compile_from_file(args.in_file, ""),
        file=args.out,
        end="")


if __name__ == "__main__":
    main()
