#include <stdint.h>
#include <stdlib.h>
struct adr_u_Generic {
void* adr_u_data;
};
struct adr_u_T {
void* adr_u_genericData;
uint_fast64_t* adr_u_length;
};
int main(void) {
int_fast8_t* adr_t1 = malloc(sizeof(int_fast8_t));
*adr_t1 = 0;
struct adr_u_Generic* adr_t9 = malloc(sizeof(struct adr_u_Generic));
adr_t9->adr_u_data = malloc(sizeof(int_fast8_t));
*(int_fast8_t*)(adr_t9->adr_u_data) = *adr_t1;
struct adr_u_Generic* adr_u_a = adr_t9;
struct adr_u_Generic* adr_t10 = malloc(sizeof(struct adr_u_Generic));
int_fast8_t* adr_t11 = malloc(sizeof(int_fast8_t));
*adr_t11 = *(int_fast8_t*)(adr_u_a->adr_u_data);
adr_t10->adr_u_data = malloc(sizeof(int_fast8_t));
*(int_fast8_t*)(adr_t10->adr_u_data) = *adr_t11;
free(adr_t11);
struct adr_u_Generic* adr_u_b = adr_t10;
int_fast16_t* adr_t2 = malloc(sizeof(int_fast16_t));
*adr_t2 = 4;
struct adr_u_Generic* adr_t12 = malloc(sizeof(struct adr_u_Generic));
adr_t12->adr_u_data = malloc(sizeof(int_fast16_t));
*(int_fast16_t*)(adr_t12->adr_u_data) = *adr_t2;
struct adr_u_Generic* adr_u_d = adr_t12;
*(int_fast16_t*)(adr_u_d->adr_u_data) = 2;
int_fast32_t* adr_t3 = malloc(sizeof(int_fast32_t));
*adr_t3 = 1;
struct adr_u_Generic* adr_t13 = malloc(sizeof(struct adr_u_Generic));
adr_t13->adr_u_data = malloc(sizeof(int_fast32_t));
*(int_fast32_t*)(adr_t13->adr_u_data) = *adr_t3;
struct adr_u_Generic* adr_u_e = adr_t13;
int_fast32_t* adr_t4 = malloc(sizeof(int_fast32_t));
*adr_t4 = 6;
free(adr_u_e->adr_u_data);
free(adr_u_e);
struct adr_u_Generic* adr_t14 = malloc(sizeof(struct adr_u_Generic));
adr_t14->adr_u_data = malloc(sizeof(int_fast32_t));
*(int_fast32_t*)(adr_t14->adr_u_data) = *adr_t4;
adr_u_e = adr_t14;
int_fast8_t* adr_t7 = malloc(sizeof(int_fast8_t));
*adr_t7 = 12;
uint_fast64_t* adr_t8 = malloc(sizeof(uint_fast64_t));
*adr_t8 = 1;
struct adr_u_T* adr_t15 = malloc(sizeof(struct adr_u_T));
adr_t15->adr_u_genericData = malloc(sizeof(int_fast8_t));
*(int_fast8_t*)(adr_t15->adr_u_genericData) = *adr_t7;
adr_t15->adr_u_length = malloc(sizeof(uint_fast64_t));
*adr_t15->adr_u_length = *adr_t8;
struct adr_u_T* adr_u_c = adr_t15;
free(adr_u_a->adr_u_data);
free(adr_u_a);
free(adr_u_b->adr_u_data);
free(adr_u_b);
free(adr_u_c->adr_u_genericData);
free(adr_u_c->adr_u_length);
free(adr_u_c);
free(adr_u_d->adr_u_data);
free(adr_u_d);
free(adr_u_e->adr_u_data);
free(adr_u_e);
free(adr_t1);
free(adr_t2);
free(adr_t3);
free(adr_t4);
free(adr_t7);
free(adr_t8);
return 0;
}