VAR_DECL = "VarDecl"
LET_DECL = "LetDecl"
FUN_DECL = "FuncDecl"
METHOD_DECL = "MethodDecl"
STRUCT_DECL = "StructDecl"
ADT_DECL = "ADTDecl"
PROTOCOL_DECL = "ProtocolDecl"
FIELD_DECL = "FieldDecl"
ASSIGNMENT = "Assignment"
RETURN = "Return"
WHILE = "While"

NAME = "Name"
SEXPR = "Expr"

BODY = "Body"
ARGS = "Args"
TYPES = "Types"
VAR_TYPES = "VarTypes"
ARG_LIST = "CallArgs"
EMPTY = "Empty"

INTEGER = "IntLiteral"

MODULE_MEMBER = "ModuleMember"
STRUCT_MEMBER = "StructMember"
PARAMETERIZED_TYPE = "ParameterizedType"
CALL = "FuncCall"

UNKNOWN = "Unknown"
