DECL = "Decl"
RETURN = "Return"
FUNC_DECL = "Func"
METHOD_DECL = "Method"
STRUCT_DECL = "Struct"
INF_DECL = "Interface"
FIELD_DECL = "Field"
ASSIGNMENT = "Assignment"

NAME = "Name"
PARAMED_TYPE = "ParamedType"
SEXPR = "Expr"

NAMES = "Names"
TYPES = "Types"
BODY = "Body"
CALL_ARGS = "CallArgs"
ARGS = "Args"

INTEGER = "IntLiteral"
STRING = "String"
REF = "Ref"
UNREF = "Unref"

MODULE_MEMBER = "ModuleMember"
STRUCT_ELEM = "StructElem"
METHOD_CALL = "MethodCall"
FUNC_CALL = "FuncCall"

EMPTY = "Empty"
