/* A packrat parser generated by PackCC 1.2.0 */

#ifndef PCC_INCLUDED__ADRIAN_PARSER_H
#define PCC_INCLUDED__ADRIAN_PARSER_H

extern UT_array* parse(StringIterator* input_string);

#ifdef __cplusplus
extern "C" {
#endif

typedef struct pcc_context_tag pcc_context_t;

pcc_context_t *pcc_create(StringIterator*auxil);
int pcc_parse(pcc_context_t *ctx, void**ret);
void pcc_destroy(pcc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* PCC_INCLUDED__ADRIAN_PARSER_H */
