#!/usr/bin/env python3

import os
import sys
import argparse
import importlib


VENDOR_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "vendor")


def main():
    sys.path.append(VENDOR_PATH)
    pipa = importlib.import_module("pipa")
    def to_obj(string):
        return {
            "parser": pipa.parser.Parser,
            "desugar": pipa.desugar.Desugar,
            "loader": pipa.loader.Loader,
            "interpreter": pipa.interpreter.Interpreter,
        }.get(string, None)

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "in_file", type=argparse.FileType("r", encoding="utf-8"))
    parser.add_argument(
        "--stop-before", type=str, help="stop before layer")
    parser.add_argument(
        "--stop-after", type=str, help="stop after layer")
    parser.add_argument(
        "--print-ast", help="print ast after translation", action="store_true")
    parser.add_argument(
        "--modules", type=str, help="where to find modules")

    args = parser.parse_args()
    pipa.compile_from_file(
        args.in_file.name, stop_before=to_obj(args.stop_before),
        stop_after=to_obj(args.stop_after), print_ast=args.print_ast,
        modules_file=args.modules)


if __name__ == "__main__":
    main()
